### ISSUE TITLE
Not working for me. Any help would be appreciated

### ISSUE THREAD

**Issue by Austin-Routt** [KM911/obsidian-execute-code-c-support#1]
Hi,

Thanks for this, but it doesn't seem to work for me. Here's what happens:

<img width="573" alt="c++ error" src="https://github.com/KM911/obsidian-execute-code-c-support/assets/7801727/29976933-bc04-4e6d-9d6e-2fa1e264e6d6">

I have clang installed: 

clang version 14.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin

Any idea what's going on here, or how I could fix it?

**Comment by KM911** [comment]
Please check your settings. You may enable "Use main function". (*^_^*)
![image](https://github.com/KM911/obsidian-execute-code-c-support/assets/86272342/fdda3dc9-0194-4af8-88c5-9fdaf2622662)

**Comment by Austin-Routt** [comment]
I've tried both. Whether I enable or disable "Use main function," I still get the same error: 

panic: runtime error: index out of range [5] with length 5

goroutine 1 [running]:
main.Execute()
	D:/CODE/go/obsidian-execute-code-c-support/main.go:47 +0x285
main.main()
	D:/CODE/go/obsidian-execute-code-c-support/main.go:67 +0x3a

**Comment by KM911** [comment]
I'm sorry that I can't reproduce your results. Can you try using the new [version](https://github.com/KM911/obsidian-execute-code-c-support/releases/tag/v0.0.4)? 
If the problem still persists, please provide a screenshot of your settings.
